volumes:
  cinesearch-express-data:
    external: true
  cine-node-modules:
    external: true
services:
  mongo:
    image: mongo:6
    volumes:
      - cinesearch-express-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://admin:admin@mongo/admin
      SIGNING_KEY: 87fe4a3fcfb60092dbaeb854a196bc3d9b190aed7930c734749e85245de698420c25f8e6899c421b4494e99459e01058de5daa9d49584cd62ec975da9aea33da
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60

  ghi:
    build:
      context: ghi
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - cine-node-modules:/app/node_modules
      - ./ghi:/app
    environment:
      REACT_APP_API_HOST: http://localhost:8000
      REACT_APP_WS_HOST: ws://localhost:8000
      WAIT_HOSTS: api:8000
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
